spring:
  application:
    name: Practice

  datasource:
    url: jdbc:mysql://localhost:3306/school_enterprise_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: "#020728Ceq"
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO

redis:
  host: localhost
  port: 6379
  password:

cos:
  client:
    accessKey:
    secretKey:
    region:
    bucket:

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: school-group

elasticsearch:
  url: 127.0.0.1:9200